name: vue_cli
version: 0.4.0
description: A CLI helper for VueDart, featuring project template and easy migrations
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://github.com/kirbyfan64/vuedart
dependencies:
  ansicolor: ^1.0.1
  args: ^1.5.0
  path: ^1.6.2
  source_maps: ^0.10.6
  source_span: ^1.4.0
executables:
  vuedart:
environment:
  sdk: ">=2.0.0 <3.0.0"
