name: vue2
version: 0.3.0
description: Vue 2.0 bindings for Dart
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://refi64.com/vuedart
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  analyzer: ^0.29.11
  barback: ^0.15.2+11
  browser: ^0.10.0+2 # demo
  dart_to_js_script_rewriter: ^1.0.3 # demo
  html: ^0.13.2
  initialize: ^0.6.2+7
  js: ^0.6.1 # demo
  source_maps: ^0.10.4
  source_span: ^1.4.0
transformers:
  - vue2
  - dart_to_js_script_rewriter
  - $dart2js:
      $exclude: [web/todo_item.dart]
      commandLineOptions: [--show-package-warnings]
