name: vuedart_site
version: 0.1.0
description: VueDart website
author: Ryan Gonzalez
dependencies:
  aspen_assets: ^0.2.0
  browser: any
  dart_to_js_script_rewriter: any
  md_to_html: ^0.1.0
  pygments: ^0.1.1
  vue: any
dependency_overrides:
  vue:
    path: ../vue
transformers:
  - md_to_html:
      template: web/template.html
  - pygments:
      classes:
        - "pre.bash, pre.dart, pre.html, pre.yaml":
            re: "(.*)"
  - vue:
      entry_points:
        - web/index.dart
        - web/pages/docs.dart
  - dart_to_js_script_rewriter
  - $dart2js:
      commandLineOptions: [--show-package-warnings]
