name: vuedart_site
version: 0.1.0
description: VueDart website
author: Ryan Gonzalez
dependencies:
  aspen_assets: ^0.2.0
  build: ^0.12.4
  js: ^0.6.1
  markdown: ^2.0.0
  protic: ^0.1.1
  vue: any
dev_dependencies:
  build_runner: any
  build_web_compilers: any
dependency_overrides:
  vue:
    path: ../vue
