name: vue2_cli
version: 0.1.0
description: A CLI helper for VueDart, featuring project template and easy migrations
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://github.com/kirbyfan64/vuedart
dependencies:
  ansicolor: ^0.0.9
  args: ^1.0.0
  path: ^1.5.0
  source_maps: ^0.10.4
  source_span: ^1.4.0
executables:
  vuedart:
environment:
  sdk: ">=1.8.0 <2.0.0"
