name: vuedart_cli
version: 0.1.0
description: A CLI helper for VueDart, featuring project template and easy migrations
author: Ryan Gonzalez
homepage: https://github.com/kirbyfan64/aspen
dependencies:
  ansicolor: ^0.0.9
  args: any
  path: ^1.5.0
  source_maps: any
  source_span: any
executables:
  vuedart:
environment:
  sdk: ">=1.8.0 <2.0.0"
