name: vuedart_example
version: 0.1.0
description: VueDart example app
author: Foo Bar
dependencies:
  browser: any
  vue: any
dependency_overrides:
  vue:
    path: ../../vue
transformers:
  - vue:
      entry_points:
        - web/index.dart
