name: vue
version: 0.3.2
description: Vue bindings for Dart
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://refi64.com/vuedart
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  analyzer: ^0.29.11
  barback: ^0.15.2+11
  csslib: ^0.14.1
  html: ^0.13.2
  initialize: ^0.6.2+7
  scopify: ^0.2.0
  source_maps: ^0.10.4
  source_span: ^1.4.0
  uuid: ^0.5.0
