name: vue_playground
version: 0.3.2
description: TODO
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://refi64.com/vuedart
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  js: ^0.6.1
  vue: any
dependency_overrides:
  vue:
    path: ../vue
dev_dependencies:
  build_runner: any
  build_web_compilers: any
