name: vue_playground
version: 0.3.2
description: TODO
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://refi64.com/vuedart
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  browser: ^0.10.0+2
  dart_to_js_script_rewriter: ^1.0.3
  js: ^0.6.1
  vue: any
dependency_overrides:
  vue:
    path: ../vue
transformers:
  - vue:
      entry_points:
        - web/index.dart
  - dart_to_js_script_rewriter
  - $dart2js:
      $exclude: [web/todo_item.dart]
      commandLineOptions: [--show-package-warnings]
