name: vue_playground
version: 0.3.2
description: TODO
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://refi64.com/vuedart
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  js: ^0.6.1
  vue: any
dependency_overrides:
  vue:
    path: ../vue
dev_dependencies:
  build_runner: ^0.7.0
  build_web_compilers: ^0.2.0
